// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvpkjpyexbogxrelrsgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2cGtqcHlleGJvZ3hyZWxyc2dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2NjE2MjUsImV4cCI6MjA1NTIzNzYyNX0.n3jgASW01wEOnPW1uF6IEENxRkfjr6ZbsiCxxkzr3NI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);